<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Suite_Askblue_Training</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>de73f9b0-d6e2-4b9a-b2af-2b97599a9cfd</testSuiteGuid>
   <testCaseLink>
      <guid>f214b530-0378-4d70-99ad-fe9b80faed68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Login_Negativo_PassIncorreta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f50b82c-12e1-4416-a8a5-7412751fd146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f498ab71-2e0a-4ee3-ac94-d6cdbfc470dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf3cfb48-2ef4-47be-b998-0521397ed917</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Login_Negativo_PassVazia</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eefd92fd-ecba-44f7-83cf-824520d14219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e84ec849-f8cb-45ae-84e9-0fc7a16d45fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1c6a8b1-80e8-4d88-a499-25bb7b33df15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Login_Negativo_UserBloqueado</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d009e595-4eb1-4866-81b7-03d812c8c1be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c01352e7-279f-49e1-a7c6-2be7d49f5e42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d43059b8-951a-46a6-9bc6-aadf122cb850</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Login_Negativo_UserPassVazio</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ededcf1f-40b9-4eba-b6f3-b512b054d828</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Login_Positivo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df90852-d39f-4c86-845d-7744bdc2469b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e214b114-9d08-48cb-9b63-b1771cfdc4c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>073d5fee-4aaa-4ef7-8924-da9254cb7215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Login_Logout/Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b30a7f1a-8a1c-4f72-94df-474b23b18ff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Add_to_Cart/Add_to_Cart_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>721587ee-805a-4768-89b7-e22bf2ee9f8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Add_to_Cart/Add_to_Cart_AleatorioUm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ae44eab6-fa89-4938-9e94-1f63c10a780b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Add_to_Cart/Add_to_Cart_AleatorioVarios</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>52e5981b-78e2-4ae6-ad5e-6413657e0703</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Add_to_Cart/Add_to_Cart_Todos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e48eb861-9153-4b22-b39b-52a42512b5da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Add_to_Cart/Add_to_Cart_Todos_Record</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6f20b68c-aea8-4fed-8ca9-c683d8adb19f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Remove_from_Cart/Remove_from_Cart_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0844fe76-346f-426c-91d8-4ef4d540746d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Remove_from_Cart/Remove_from_Cart_AleatorioUm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ffec1daf-ff9a-4594-972b-8e02a90ac6e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Remove_from_Cart/Remove_from_Cart_AleatórioVários</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0cfcf2b9-66b5-41c2-af24-b6963e56491f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Remove_from_Cart/Remove_from_Cart_Todos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f4a4e4ee-18c6-4dbe-801a-171aaae8a14e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Ordenar/Ordernar_High_to_Low</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>83a2d768-dd70-4ed4-b29a-42b77e1a0467</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Finalizar_CompraE2E/Finalizar_Compra_1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eea8a1e-5ab8-42c4-95ea-739d457d0cbd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0330d657-7b5a-4daa-b3f5-69554cc09cde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Finalizar_CompraE2E/Finalizar_Compra_Record</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f8abe31a-12db-4641-9bbb-c5c1131bd5e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Askblue_Training/Finalizar_CompraE2E/Finalizar_Compra_Todos</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e85ef3cf-4fc8-4a14-95a8-2b0abe384e38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150145a2-9ff9-487a-a490-b7ccd3426833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad7f2d5a-6b37-40f0-a8e1-fba8e9828fbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06127255-e582-4e06-a968-24d76c3417bf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
